---
# tasks file for ansible-role-slurm-slurm-spank-gpu

- name: Make sure all needed packages are installed
  package: 
    name: "{{ slurm_spank_gpu_dependencies }}"
    state: present
      
- name: Let's copy local rpm to client
  copy:
    src: "files/{{ slurm_spank_lua_plugin }}" 
    mode: 0644
    dest: /tmp
  notify: remove local rpm

- name: Install Self-builded spank-lua plugin
  package:
    name: "/tmp/{{ slurm_spank_lua_plugin }}"
    state: present

- name: Let's place new spank-module in-place
  copy: 
    src: "files/{{ slurm_gpu_spank_plugin }}"
    dest: /etc/slurm/lua.d
  notify: restart slurmd
